In [15]:
import numpy as np
print(np.__version__)

2.2.6


In [16]:
list_1=[1,2,3,4]
print(list_1)
#we want vectorized computation means double each element shoudl double 
print(list_1*2)

[1, 2, 3, 4]
[1, 2, 3, 4, 1, 2, 3, 4]


In [17]:
arr=np.array([1,2,3,4])
print(arr*2)
print(type(arr))

[2 4 6 8]
<class 'numpy.ndarray'>


In [18]:
# multidimentional array
#0 dimension
arr=np.array('A')
print(arr.ndim)
arr1=np.array(['A','B','C'])
print(arr1.ndim)
arr2=np.array([['A','B','C'],['C','D','E']])
print(arr2.ndim)
arr3=np.array([[['A','B','C'],['C','D','E']],
               [['A','B','C'],['C','D','E']]])
print(arr3.ndim)

print(arr3.shape) #gives depth, rows and cols
print(arr3[0][1][1])
#or
print(arr3[0,1,1])

0
1
2
3
(2, 2, 3)
D
D


In [ ]:
#slicing
arr=np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12],
             [13,14,15,16]])
#print 1st row
print(arr[0])
print(arr[0:3])
print('New')
print(arr[0:4:2])
print('New')
print(arr[::2])
print('New')
print(arr[::-1]) #prints all rows reversed if -2 is used every second row prints in reverse

[1 2 3 4]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
New
[[ 1  2  3  4]
 [ 9 10 11 12]]
New
[[ 1  2  3  4]
 [ 9 10 11 12]]
New
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [29]:
arr=np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12],
             [13,14,15,16]])
#select all columsn with index 0
print(arr[:,0])
#first three columns
print('New')
print(arr[:,1:3])
print('new')
print(arr[:,::2])
print('new')
#cols in reverse
print(arr[:,::-1])

[ 1  5  9 13]
New
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
new
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]
new
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [34]:
arr=np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12],
             [13,14,15,16]])
#first 2 rows with 2 cols
print(arr[0:2,0:2])
#selecting 3 4 7 8
print(arr[:2,2:])
print(arr[2:,:2])

[[1 2]
 [5 6]]
[[3 4]
 [7 8]]
[[ 9 10]
 [13 14]]


In [35]:
#arithmetic
#Scalar arithemtic
arr=np.array([1,2,3])
print(arr+1)
print(arr-2)
print(arr*3)
print(arr**5)

[2 3 4]
[-1  0  1]
[3 6 9]
[  1  32 243]


In [38]:
#vecotrized compuataion 
arr=np.array([1,2,3])
print(np.sqrt(arr))
arr1=np.array([1.01,2.6,34.3])
print(np.floor(arr))
print(np.round(arr))


[1.         1.41421356 1.73205081]
[1 2 3]
[1 2 3]


In [40]:
#given radii calculate the corresponding area
radii=np.array([3,2,4])
print(np.pi*np.square(radii))

[28.27433388 12.56637061 50.26548246]


In [42]:
#Element wise
n1=np.array([1,2,3])
n2=np.array([4,5,6])
print(n1+n2)
print(n1-n2)
print(n1*n2)
print(n1**n2)
print(n1/n2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[  1  32 729]
[0.25 0.4  0.5 ]


In [44]:
#Comparasion
score=np.array([1,2,3,4])
print(score==2)
print(score>2)

[False  True False False]
[False False  True  True]


In [46]:
#Broadcasting allows numpy to perform operations on array
#with diff shape allowing arrays to expand dimension virtually
#so they match the larger's array shape
a1=np.array([[1,2,3,4]])
a2=np.array([[1],[2],[3],[4]])
print(a1.shape)
print(a2.shape)

(1, 4)
(4, 1)
